spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:${DB_NAME}://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  url:
    base-documents-api: "http://localhost:8080"
    api-documents: "/api/v1/documents"
  httpclient5:
    connection-request-timeout-second: 5
    response-timeout-second: 10

  resilience4j:
    retry:
      max-attempts: 3
      wait-second: 2
    circuit-breaker:
      rate-threshold: 50
      wait-second: 10
generator:
  document-create: 10

executors:
  min-thread: 5
  max-thread: 10
  queue-task: 25
  thread-name: "executors-worker"
  wait-for-task: true
  await-termination-seconds: 30

scheduled:
  batch-size: 500
  submit:
    name: "SUBMIT-worker"
    cron: ""
  approve:
    name: "APPROVE-worker"
    cron: ""



